AWSTemplateFormatVersion: "2010-09-09"
Description: >
  OIDC Provider Settings for GitHub Actions

Resources:
  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList:
        - "sts.amazonaws.com"
